# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services_pb2 as services__pb2


class NstmStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PullTask = channel.unary_unary(
        '/com.nextsmarty.nstm.rpc.Nstm/PullTask',
        request_serializer=services__pb2.PullTaskRequest.SerializeToString,
        response_deserializer=services__pb2.PullTaskRespone.FromString,
        )
    self.DoneTask = channel.unary_unary(
        '/com.nextsmarty.nstm.rpc.Nstm/DoneTask',
        request_serializer=services__pb2.DoneTaskRequest.SerializeToString,
        response_deserializer=services__pb2.DoneTaskRespone.FromString,
        )
    self.Register = channel.unary_unary(
        '/com.nextsmarty.nstm.rpc.Nstm/Register',
        request_serializer=services__pb2.WorkerRegisterRequest.SerializeToString,
        response_deserializer=services__pb2.WorkerRegisterRespone.FromString,
        )
    self.SubmitTask = channel.unary_unary(
        '/com.nextsmarty.nstm.rpc.Nstm/SubmitTask',
        request_serializer=services__pb2.SubmitTaskRequest.SerializeToString,
        response_deserializer=services__pb2.SubmitTaskRespone.FromString,
        )
    self.DeleteTask = channel.unary_unary(
        '/com.nextsmarty.nstm.rpc.Nstm/DeleteTask',
        request_serializer=services__pb2.DeleteRequest.SerializeToString,
        response_deserializer=services__pb2.DeleteTaskRespone.FromString,
        )


class NstmServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PullTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoneTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NstmServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PullTask': grpc.unary_unary_rpc_method_handler(
          servicer.PullTask,
          request_deserializer=services__pb2.PullTaskRequest.FromString,
          response_serializer=services__pb2.PullTaskRespone.SerializeToString,
      ),
      'DoneTask': grpc.unary_unary_rpc_method_handler(
          servicer.DoneTask,
          request_deserializer=services__pb2.DoneTaskRequest.FromString,
          response_serializer=services__pb2.DoneTaskRespone.SerializeToString,
      ),
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=services__pb2.WorkerRegisterRequest.FromString,
          response_serializer=services__pb2.WorkerRegisterRespone.SerializeToString,
      ),
      'SubmitTask': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitTask,
          request_deserializer=services__pb2.SubmitTaskRequest.FromString,
          response_serializer=services__pb2.SubmitTaskRespone.SerializeToString,
      ),
      'DeleteTask': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTask,
          request_deserializer=services__pb2.DeleteRequest.FromString,
          response_serializer=services__pb2.DeleteTaskRespone.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.nextsmarty.nstm.rpc.Nstm', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
